algorytm:
    path: /ktory/alg/zastosowac
    controller: App\Controller\KtoryAlgZastosowacController::index
hello_page:
  path: /
  controller: App\Controller\HelloPageController::index

dodanie_do_bazy:
  path: /article/admin
  controller: App\Controller\ArticleAdminContorller::index
